backend:
  name: git-gateway
local_backend: true
media_folder: public/images
public_folder: "/images"
collections:
  - label: Pages
    name: pages
    format: json
    description: This collection allows editing website content
    create: false
    delete: false
    editor:
      preview: false
    files:
      - label: Home Page
        name: home
        file: "content/pages/home.json"
        fields:
          - label: Our Vision
            name: vision
            widget: text
          - label: Our Mission
            name: mission
            widget: text
          - label: Stats
            name: stats
            widget: list
            max: 4
            min: 4
            fields:
              - label: Number Text
                name: numtext
                widget: string
              - label: Subject Text
                name: subtext
                widget: string
          - label: Testimonials
            name: testimonials
            widget: list
            max: 4
            min: 4
            fields:
              - label: Text
                name: text
                widget: text
              - label: Author
                name: author
                widget: string
              - label: Author Image
                name: authorImg
                widget: image
  - label: Tags
    name: tags
    label_singular: Tag
    format: json
    description: Tags for events
    folder: content/tags
    create: true
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Color
        name: color
        widget: color
  - label: Events
    name: events
    label_singular: Event
    format: json
    description: Past, current and future Events that will be shown on the events page.
    folder: content/events
    slug: "{{year}}-{{title}}"
    create: true
    editor:
      preview: false
    fields:
      - label: Club
        name: club
        widget: select
        options:
          - Student Branch
          - WIE
          - Computer Society
      - label: Title
        name: title
        widget: string
      - label: Cover Image
        name: image
        widget: image
      - label: Description
        name: description
        widget: markdown
      - label: Start Date Time
        name: start_datetime
        widget: datetime
        date_format: DD.MM.YYYY
        time_format: HH:mm
        format: LLL
        picker_utc: false
      - label: End Date Time
        name: end_datetime
        widget: datetime
        date_format: DD.MM.YYYY
        time_format: HH:mm
        format: LLL
        picker_utc: false
      - label: Contacts
        name: contacts
        widget: list
        fields:
          - label: Full Name
            name: name
            widget: string
          - label: Mobile No
            name: mobno
            widget: string
      - label: Tags
        name: tags
        widget: relation
        multiple: true
        collection: tags
        search_fields:
          - title
        value_field: "title"
      - label: Team Size
        name: team_size
        widget: string
        required: false
      - label: Fee
        name: fee
        widget: string
        required: false
      - label: Prize
        name: prize
        widget: string
        required: false
