backend:
  name: git-gateway
local_backend: true
media_folder: public/images
public_folder: /images

collections:
  - label: Projects
    name: projects
    label_singular: Project
    description: Projects that will be shown on the project spotlight page.
    folder: content/projects/
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Author
        name: authors
        widget: list
        fields:
          - label: Full Name
            name: name
            widget: string
          - label: GitHub Link
            name: github
            widget: string
          - label: LinkedIn Link
            name: linkedin
            widget: string
            required: false
          - label: Twitter Link
            name: twitter
            widget: string
            required: false
          - label: Instagram Link
            name: instagram
            widget: string
            required: false
          - label: Website
            name: website
            widget: string
            required: false
          - label: Other
            name: other
            widget: string
            required: false
      - label: Project GitHub Link
        name: github
        widget: string
      - label: Summary
        name: summary
        widget: string
  - label: Events
    name: events
    label_singular: Event
    description: Past, current and future Events that will be shown on the events page.
    folder: content/events
    create: true
    fields:
      - label: Club
        name: club
        widget: select
        options: ["Student Branch", "WIE", "Computer Society"]
      - label: Title
        name: title
        widget: string
      - label: Cover Image
        name: image
        widget: image
      - label: Description
        name: description
        widget: markdown
      - label: Start Date Time
        name: start_datetime
        widget: datetime
        date_format: DD.MM.YYYY
        time_format: HH:mm
        format: LLL
        picker_utc: false
      - label: End Date Time
        name: end_datetime
        widget: datetime
        date_format: DD.MM.YYYY
        time_format: HH:mm
        format: LLL
        picker_utc: false
      - label: Contacts
        name: contacts
        widget: list
        fields:
          - label: Full Name
            name: name
            widget: string
          - label: Mobile No
            name: mobno
            widget: string
      - label: Tags
        name: tags
        widget: 
      - label: Team Size
        name: team_size
        widget: string
        required: false
      - label: Fee
        name: fee
        widget: string
        required: false
      - label: Prize
        name: prize
        widget: string
        required: false
